name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Add aarch64-apple-ios target
      run: rustup target add aarch64-apple-ios
       
    - name: Generate XCFramework
      run: make xcframework
