name: Generate XCFramework

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Add aarch64-apple-ios target
      run: rustup target add aarch64-apple-ios
      
    - name: Add x86_64-apple-ios target
      run: rustup target add x86_64-apple-ios
       
    - name: Generate XCFramework
      run: make xcframework
      
    - name: Zip XCFramework
      run: zip -r test.xcframework.zip target/*.xcframework/
      
    - uses: actions/upload-artifact@v3
      with:
        name: xcframework
        path: test.xcframework.zip
