name: Generate XCFramework

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest
    if: ${{ false }}  # disable for now
    steps:
    - uses: actions/checkout@v3
    
    - name: Add aarch64-apple-ios target
      run: rustup target add aarch64-apple-ios
    - name: Add x86_64-apple-ios target
      run: rustup target add x86_64-apple-ios
       
    - name: Generate XCFramework
      run: make xcframework
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: xcframework
        path: target/*.xcframework/
        
    - name: Dispatch workflow in Swift package repository
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.SWIFT_PACKAGE_TOKEN }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: '${{ secrets.SWIFT_PACKAGE_OWNER }}',
            repo: '${{ secrets.SWIFT_PACKAGE_REPO }}',
            workflow_id: 'main.yml',
            ref: 'master',
            inputs: {
              url: 'https://nightly.link/JJTech0130/xcframework-template/actions/runs/${{ github.run_id }}/xcframework.zip'
            }
          })
          
  deploy:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3
    
    - name: copy template out
      run: cp Package.template.swift ..
      
    - name: extract current branch
      run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
      id: extract_branch
    
    - name: create output branch
      run: git switch --orphan swift/${{ steps.extract_branch.outputs.branch }}
      
    - name: copy template back
      run: cp ../Package.template.swift Package.swift
      
    - name: assemble URL
      run: echo "::set-output name=url::https://nightly.link/${{ github.repository }}/actions/runs/${{ github.run_id }}/xcframework.zip"
      id: assemble_url
      
    - name: calculate hash
      run: echo "::set-output name=hash::$(curl -sL ${{ steps.assemble_url.outputs.url }} | shasum -a 256 | head -c 64)"
      id: calculate_hash
      
    - name: replace $URL
      run: sed -i -e 's|$URL|${{ steps.assemble_url.outputs.url }}|g' Package.swift
      
    - name: replace $CHECKSUM
      run: sed -i -e 's/$CHECKSUM/${{ steps.calculate_hash.outputs.hash }}/g' Package.swift
      
    - name: cat manifest
      run: cat Package.swift
      
    #- name: check if output branch exists
    #  run: |
    #    git show-ref --verify --quiet refs/heads/swift/${{ steps.extract_branch.outputs.branch }}
    #    echo "::set-output name=should_create::$?"
    #  id: branch_exists
      
    #- name: switch to output branch
    #  run: |
    #    echo ${{ steps.branch_exists.outputs.should_create }}
    #    if [ ${{ steps.branch_exists.outputs.should_create }} -ne 0 ]; then
    #      echo "creating branch"
    #    else
    #      echo "branch exists"
    #    fi
        
        
   # - name: switch to output branch
     # run: |
   #     echo "swift/${{ steps.extract_branch.outputs.branch }}"
      #echo "::set-output name=action_fruit::strawberry"

    #- name: check for branch
    #  env:
    #    branch: 
    #  run: |
    #    git show-ref --verify --quiet refs/heads/<branch-name>
    #    ret=$?
    #    if [ $ret -ne 0 ]; then
    #      echo "
    #    else
    #      echo "In Else"
    ##   fi
