name: Generate XCFramework

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Add aarch64-apple-ios target
      run: rustup target add aarch64-apple-ios
      
    - name: Add x86_64-apple-ios target
      run: rustup target add x86_64-apple-ios
       
    - name: Generate XCFramework
      run: make xcframework
      
    - uses: actions/upload-artifact@v3
      with:
        name: xcframework
        path: target/*.xcframework/
        
  deploy:
  
    runs-on: ubuntu-latest
    needs: [build]
    environment: production
    
    steps:
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3
      
    - name: Upload as release
      uses: softprops/action-gh-release@v1
      with:
          files: xcframework/*.xcframework

    
