name: Generate XCFramework

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Add aarch64-apple-ios target
      run: rustup target add aarch64-apple-ios
      
    - name: Add x86_64-apple-ios target
      run: rustup target add x86_64-apple-ios
       
    - name: Generate XCFramework
      run: make xcframework
      
    - uses: actions/upload-artifact@v3
      with:
        name: xcframework
        path: target/*.xcframework/
        
    - uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.SIDESTORER_TOKEN }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'JJTech0130',
            repo: 'swift-xcframework',
            workflow_id: 'main.yml',
            ref: 'master',
            inputs: {
              url: 'https://nightly.link/JJTech0130/xcframework-template/actions/runs/${{ github.run_id }}/xcframework.zip'
            }
          })
